name: Build
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: nw874-256m
      - name: Install
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler
      - name: Chmod
        run: chmod +x build.sh
      - name: Build
        run: SOC=mt7981 BOARD=360t7 ./build.sh
      - name: Package
        run: |
          DATE=$(date +%Y%m%d)
          mkdir out
          cp output/*.bin out/
          zip -j 360t7-uboot-$DATE.zip out/*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 360T7-Uboot
          tag_name: ${{ github.sha }}
          draft: false
          prerelease: false
          files: 360t7-uboot-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
