name: Auto Sync Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Sync & Apply NW874 Config
        run: |
          set +e
          git config --global user.name "actions"
          git config --global user.email "actions@github.com"

          git remote remove upstream || true
          git remote add upstream https://github.com/Yuzhii0718/bl-mt798x-dhcpd.git
          git fetch upstream

          git checkout -B nw874-256m upstream/master

          # 自动写入你的固定配置
          echo "CONFIG_NMBM_MAX_BLOCKS=32" >> configs/nw874_defconfig
          echo 'CONFIG_MTDPARTS_DEFAULT="nmbm0:1024k(bl2),512k(u-boot-env),2048k(factory),2048k(fip),232M(ubi),1M(stock-config),512k(stock-factory),4M(stock-log)"' >> configs/nw874_defconfig

          git add .
          git commit -m "auto sync upstream + apply nw874 256m config" || true
          git push -f origin nw874-256m || true

          exit 0
